[package]
name = "anchr"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1", features = ["derive"] }
toml = "0.8"
openssl = "0.10"
quinn = "0.10"
tokio = { version = "1", features = ["full"] }
rustls = "0.21"